apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: domdom-com-tls
spec:
  secretName: domdom-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: domdom.com
  dnsNames:
    - domdom.com
    - www.domdom.com